### ISSUE TITLE
Library includes/links pro components

### ISSUE THREAD

**Issue by INPUTsys-Chris** [F0rce/signature-widget#1]
**Describe the bug**
The library unnecessarily links the Vaadin pro components.

**Additional context**
You should use "vaadin-core" as artifact id instead of "vaadin".

**Comment by F0rce** [comment]
Hei @INPUTsys-Chris,

shoot, I totally missed that. Thanks for the information. Will change it instantly and upload it as version 1.0.1.

Give me a maximum of 30 minutes.

Thank you,
David

**Comment by INPUTsys-Chris** [comment]
Wow that was fast! Also I like the "good first issue" thing because it's not only a good first issue for developers but also the first issue in the repository :)

**Comment by INPUTsys-Chris** [comment]
I've seen your changes. I guess the dependency artifact should also be changed.
I wanted to do it by myself but creating a fork seems like an overkill for a small issue like that

**Comment by F0rce** [comment]
No worries,

i'm always super active contributing to the things I create. The version 1.0.1 has been uploaded.

Thanks for showing me,
David

**Comment by INPUTsys-Chris** [comment]
I guess this should also be changed to vaadin-core:

```
<dependencies>
        <dependency>
            <groupId>com.vaadin</groupId>
            <!-- Replace artifactId with vaadin-core to use only free components -->
            <artifactId>vaadin</artifactId>
            <exclusions>
```

**Comment by F0rce** [comment]
I changed the whole main dependency, so I think that it would be enough. If not, I will upload these changes with the next update. dont want to upload so many versions.
