### ISSUE TITLE
clear() does not remove the imageUri or base64 String

### ISSUE THREAD

**Issue by KaijuDeluxe** [F0rce/signature-widget#29]
The .clear() Method should remove the base64 content, so you can check if the signature was removed

**Comment by F0rce** [comment]
Hei @KaijuDeluxe 

thanks for informing be about this issue. As far as I know it should trigger and force a new sync of the cleared signature as soon as the method is called, but I will further investigate.

Have a great day,
David

**Comment by KaijuDeluxe** [comment]
Thank you. Yes the image will ve removed from the widget (the drawing) but the base64 attribut still got some data. Before i sign anything, the base64 and imageUri is null. This should it be also after clear()

**Comment by F0rce** [comment]
Hello @KaijuDeluxe, 

sorry for the late answer. The imgaueUri will always be present, due to my custom event. But I added a `isEmpty()` Method, which will tell you if something is in the signature or not. It will be availible later today with the 2.0.0 release.

Have a great day,
David

**Comment by F0rce** [comment]
https://vaadin.com/directory/component/signature-widget/2.0.0
