### ISSUE TITLE
ValueChangeEvent Support

### ISSUE THREAD

**Issue by chrisw73** [F0rce/signature-widget#308]
Hi!

Here https://github.com/F0rce/signature-widget/issues/44 someone requested an "isEmpty" feature.
I think it would be even nicer to attach a ValueChangeListener.

We have a next-button on the same screen as the signature-pad, which just should become enabled, if a signature has been done.
Currently we use: 
signatureField.getElement().addEventListener("click", domEvent -> this.nextButton.setEnabled(true));

which does the job quite well.

Have you considered extending AbstractField instead of Component and add ValueChangeListener Support?

Regards,
Chris

**Comment by F0rce** [comment]
This has been implented as today with Version [v3.1.0](https://vaadin.com/directory/component/signature-widget/3.1.0). Sorry for the late reply. 

If you have any question about the new listener please re-open or open a new one :)
