### ISSUE TITLE
Check if the Signature is empty

### ISSUE THREAD

**Issue by HHA-Abacus** [F0rce/signature-widget#44]
Hi David,

would it be possible to provide information about whether changes has been made to the signature? Right now I cannot determine if there is a signature or not as I always get a picture by calling getImageBase64().

Would really appreciate this feature :)

thanks, Holger

**Comment by F0rce** [comment]
Small Update:
I added a method `isEmpty()` which returns a boolean to see if the signature is empty or not.

**Comment by F0rce** [comment]
https://vaadin.com/directory/component/signature-widget/2.0.0

**Comment by HHA-Abacus** [comment]
Hello David,

that would be great. Thanks a lot.

A good day for u 2,

Holger

Von: David Dodlek ***@***.***>
Gesendet: Montag, 29. März 2021 15:20
An: F0rce/signature-widget ***@***.***>
Cc: Holger Hähnel ***@***.***>; Mention ***@***.***>
Betreff: Re: [F0rce/signature-widget] Check if the Signature is empty (#44)


Hello @HHA-Abacus<https://github.com/HHA-Abacus>,

I am currently working on a new release for the signature widget, due to Polymer 3 going end of life. I am using Lit-Element for the frontend from now on.

I will try to maybe make a custom event listener, so you could "see" when the signature changes. Would that be fitting for your request/needs?

Have a great day,
David
